#!/bin/sh
#
### BEGIN INIT INFO
# Provides:		date-sync
# Required-Start:	$remote_fs $syslog $networking
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	Start and stop the date-sync daemon
### END INIT INFO
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=date-sync
DESC="Date Sync"
LOGFILE=/tmp/date-sync.log

start() {
	echo -n "Starting $DESC: "
	# Get the current UTC time from worldtimeapi.org
	current_time=$(curl -s "http://worldtimeapi.org/api/timezone/Etc/UTC" | sed -n 's/.*"datetime":"\([^.]*\).*/\1/p')

	# Format the time string
	formatted_time=$(date -u -d "$current_time" '+%a %b %d %H:%M:%S UTC %Y')

	# Set the system time
	date -u -s "$formatted_time"

	echo "Time synchronization completed. New time: $formatted_time"
	echo "$NAME."
}


case "$1" in
  start)
        start > $LOGFILE 2>&1
        ;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N start" >&2
	exit 1
	;;
esac
exit 0
