#!/bin/sh
### BEGIN INIT INFO
# Provides:          cvm-reverse-proxy-server
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start CVM Reverse Proxy Server at boot time
# Description:       Enable CVM Reverse Proxy Server service.
### END INIT INFO

DAEMON=/usr/bin/proxy-server
NAME=cvm-reverse-proxy-server
DESC="CVM Reverse Proxy Server"
DAEMON_ARGS="--listen-addr=0.0.0.0:7936 --target-addr=http://localhost:14727 --server-attestation-type azure-tdx"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
SYSTEM_API_FIFO=/var/volatile/system-api.fifo

log() {
    if [ -p $SYSTEM_API_FIFO ]; then
        date_log() {
            echo -n ""
        }
    else
        date_log() {
            echo -n "$(date): "
        }
    fi
    echo "$(date_log)$1" | tee -a $SYSTEM_API_FIFO
}

start() {
    log "Starting $NAME"
    start-stop-daemon -S --make-pidfile -p $PIDFILE -m -b --exec /bin/sh -- -c "exec $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1"
    log "Started $NAME"
}

stop() {
    log "Stopping $NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    log "Stopped $NAME"
}

restart() {
    log "Restarting $NAME"
    stop
    sleep 1
    start
    log "Restarted $NAME"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
