#!/bin/sh
### BEGIN INIT INFO
# Provides:          system-api
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start System API at boot time
# Description:       Enable System API service.
### END INIT INFO

DAEMON=/usr/bin/system-api
NAME=system-api
DESC="System API Service"
DAEMON_ARGS="--config /etc/system-api/systemapi-config.toml"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

start() {
    mkdir -p /persistent/rbuilder
    echo -n "Starting $DESC: "
    start-stop-daemon -S --make-pidfile -p $PIDFILE -m -b -a $DAEMON -- $DAEMON_ARGS > $LOGFILE 2>&1
    echo "$NAME."
    # Wait for the service to start
    sleep 1
}

stop() {
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    echo "$NAME."
}

restart() {
    echo "Restarting $DESC: "
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
