#!/bin/sh
### BEGIN INIT INFO
# Provides:          system-api
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start System API at boot time
# Description:       Enable System API service.
### END INIT INFO

DAEMON=/usr/bin/system-api
NAME=system-api
DESC="System API Service"
DAEMON_ARGS="--config /etc/system-api/systemapi-config.toml"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
SYSTEM_API_FIFO=/var/volatile/system-api.fifo

log() {
    if [ -p $SYSTEM_API_FIFO ]; then
        date_log() {
            echo -n ""
        }
    else
        date_log() {
            echo -n "$(date): "
        }
    fi
    echo "$(date_log)$1" >&2 | tee -a $SYSTEM_API_FIFO
}

start() {
    mkdir -p /persistent/rbuilder /persistent/system-api
    log "Starting $NAME"
    if [ -f "$SYSTEM_API_FIFO" ]; then
        mv $SYSTEM_API_FIFO $SYSTEM_API_FIFO.bak
    fi
    start-stop-daemon -S --make-pidfile -p $PIDFILE -m -b --exec /bin/sh -- -c "exec $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1"
    # Wait for the service to start
    sleep 2
    if [ -f "$SYSTEM_API_FIFO.bak" ]; then
        cat $SYSTEM_API_FIFO.bak > $SYSTEM_API_FIFO
        rm -f $SYSTEM_API_FIFO.bak
    fi
    chmod 644 $LOGFILE
    log "Started $NAME"
}

stop() {
    log "Stopping $NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $SYSTEM_API_FIFO
    rm -f $PIDFILE
    log "Stopped $NAME"
}

restart() {
    log "Restarting $NAME"
    stop
    sleep 1
    start
    log "Restarted $NAME"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|force-reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
